const test=require('node:test'),assert=require('node:assert/strict');
const {setup}=require('./mock.cjs'),S=require('../src/i18n'),L=require('../src/locales');
test('all six languages have complete nonempty translations',()=>{assert.equal(Object.keys(S).length,6);for(const [language,dict]of Object.entries(S)){assert.deepEqual(Object.keys(dict).sort(),Object.keys(S.en).sort(),language);for(const value of Object.values(dict))assert.ok(typeof value==='string'&&value.trim());}});
test('app language and regional aliases resolve predictably',()=>{for(const [input,expected]of [['es-MX','es'],['de_AT','de'],['pt_BR','pt-BR'],['pt','pt-BR'],['pt-PT','pt-BR'],['fr-CA','fr'],['ru-RU','ru'],['EN-us','en'],['ja','en'],['','en']])assert.equal(L.resolve(input),expected,input);assert.equal(L.choose('de','fr'),'de');});
test('official Obsidian language wins over browser and legacy storage',()=>{const s=setup({getLanguage:()=> 'pt-BR',storedLanguage:'de',navigatorLanguage:'ru'});s.plugin.settings.freeLanguage='auto';assert.equal(s.plugin.lang(),'pt-BR');s.plugin.settings.freeLanguage='es';assert.equal(s.plugin.lang(),'es');});
test('old Obsidian fallback tolerates blocked local storage',()=>{const legacy=setup({storedLanguage:'de-AT',navigatorLanguage:'ru'});legacy.plugin.settings.freeLanguage='auto';assert.equal(legacy.plugin.lang(),'de');const blocked=setup({getLanguage:()=>{throw Error('not available')},storageError:true,navigatorLanguage:'fr-CA'});blocked.plugin.settings.freeLanguage='auto';assert.equal(blocked.plugin.lang(),'fr');});
test('missing translation falls back to English',()=>{assert.equal(L.text({en:{save:'Save'},es:{}},'es','save'),'Save');assert.equal(L.text(S,'unsupported','save'),'Save');});
test('calendar dates format correctly for all six locales',()=>{const expected={ru:'07.10.2026',en:'10/07/2026',es:'07/10/2026',de:'07.10.2026','pt-BR':'07/10/2026',fr:'07/10/2026'};const s=setup();for(const [lang,value]of Object.entries(expected)){s.plugin.settings.freeLanguage=lang;assert.equal(s.plugin.formatDate('2026-10-07'),value,lang);assert.equal(s.plugin.formatDate('2026-02-31'),'');}});
test('language selection saves, reloads, and updates command labels',async()=>{const s=setup();let stored;s.plugin.saveData=async value=>stored=JSON.parse(JSON.stringify(value));s.plugin.openCommand={name:''};s.plugin.newTaskCommand={name:''};const tab=new s.views.Settings(s.plugin.app,s.plugin);tab.display();const dropdown=s.settingRows.find(x=>Object.keys(x.options).length);assert.deepEqual(Object.keys(dropdown.options).sort(),['auto',...Object.keys(L.languages)].sort());await dropdown.change('de');assert.equal(stored.freeLanguage,'de');assert.equal(s.plugin.openCommand.name,S.de.openCommand);assert.equal(s.plugin.newTaskCommand.name,S.de.newTaskCommand);const reload=setup();reload.plugin.loadData=async()=>stored;await reload.plugin.initialize();assert.equal(reload.plugin.lang(),'de');});
for(const language of Object.keys(S))test(`board, forms, menus and validation render in ${language}`,async()=>{
 const s=setup();s.plugin.settings.freeLanguage=language;const task=await s.add('User title stays unchanged',{date:'2026-10-07',recurrence:'daily'});
 const board=new s.views.Board({},s.plugin);await board.render();assert.deepEqual(board.containerEl.querySelectorAll('h3').map(x=>x.textContent),['backlog','today','done'].map(k=>S[language][k]));assert.ok(board.containerEl.textContent.includes(task.title));
 board.taskMenu({},task);assert.ok(s.menus[0].items.some(x=>x.title===S[language].delete));assert.ok(s.menus[0].items.some(x=>x.title===S[language].openNote));
 const modal=new s.views.TaskModal(s.plugin);await modal.onOpen();const fields=modal.contentEl.querySelectorAll('.mpt-field');assert.ok(fields.some(x=>x.children[0].textContent===S[language].date));const save=modal.contentEl.querySelectorAll('button').find(x=>x.textContent===S[language].save);await save.onclick();assert.equal(s.notices.at(-1),S[language].titleRequired);
 const project=new s.views.ProjectModal(s.plugin);project.onOpen();assert.ok(project.contentEl.textContent.includes(S[language].color));
});
